services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
    ports:
      - '5555:5555'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
